threadCount: 20
entryCount: 10000
batchCount: 2000
maxValueSize: 800
minValueSize: 200
hotSetPercentage: 99
rounds: 15
readPercentage: 90
updatePercentage: 7
searchPercentage: 3
ehcacheFileURL: ehcache.xml
ehcacheFileCacheName: myTestCache